### ISSUE TITLE
[Dependency]: Scipy API changes after 1.14 

### ISSUE THREAD

**Issue by tanlin2013** [henhans/dmft_tutorial#1]
Dear Tsung-Han,

I just want to point out there is an API change in Scipy after Ver. 1.14.  

<img width="891" alt="Screenshot 2024-08-09 at 6 18 08 PM" src="https://github.com/user-attachments/assets/549afa3c-532d-4d5c-a433-a4e5a85176fb">

https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html#deprecated-features

**Comment by henhans** [comment]
Dear Tao-Lin,

Thanks for pointing out. They are now adapted to simpson.

Best,
Tsung-Han
